apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - common
  - bases/ecr.services.k8s.aws_pullthroughcacherules.yaml
  - bases/ecr.services.k8s.aws_repositories.yaml
  - bases/ecr.services.k8s.aws_repositorycreationtemplates.yaml
