apiVersion: v1
name: ecr-chart
description: A Helm chart for the ACK service controller for ecr
version: v0.0.6
appVersion: v0.0.6
home: https://github.com/aws-controllers-k8s/ecr-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/ecr-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: ecr Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ecr-maintainer
keywords:
  - aws
  - kubernetes
  - ecr
